;;; company-cabal-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-cabal.el

(autoload 'company-cabal "company-cabal" "\
`company-mode' completion back-end for `haskell-cabal-mode'.
Provide completion info according to COMMAND and ARG.  IGNORED, not used.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-cabal" '("company-cabal-"))


;;; Generated autoloads from company-cabal-fields.el

(register-definition-prefixes "company-cabal-fields" '("company-cabal--"))

;;; End of scraped data

(provide 'company-cabal-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-cabal-autoloads.el ends here
