;;; abs-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from abs-mode.el

(autoload 'abs-mode "abs-mode" "\
Major mode for editing Abs files.

The hooks `prog-mode-hook' and `c-mode-common-hook' are run at
mode initialization, then `abs-mode-hook'.

The following keys are set:
\\{abs-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.abs\\'" . abs-mode))
(register-definition-prefixes "abs-mode" '("abs-"))

;;; End of scraped data

(provide 'abs-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; abs-mode-autoloads.el ends here
