;;; company-ghci-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-ghci.el

(autoload 'company-ghci "company-ghci" "\
Company backend that provides completions using the current ghci process.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-ghci" '("company-ghci/"))

;;; End of scraped data

(provide 'company-ghci-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-ghci-autoloads.el ends here
