;;; change-inner-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from change-inner.el

(autoload 'change-inner "change-inner" "\


(fn ARG)" t)
(autoload 'copy-inner "change-inner" nil t)
(autoload 'change-outer "change-inner" "\


(fn ARG)" t)
(autoload 'copy-outer "change-inner" nil t)
(register-definition-prefixes "change-inner" '("change-" "ci--flash-region"))

;;; End of scraped data

(provide 'change-inner-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; change-inner-autoloads.el ends here
